import { VitalEventRecord, GeneralPopulationStats } from './types';

export const initialGeneralPopulation: GeneralPopulationStats = {
  villageTotalPopulation: 586,
  villageFemalePopulation: 308,
  villageMalePopulation: 278,
  villageTotalFamilies: 124,
  villageTotalRoofs: 98,
  votingAgePopulation: 426,
  votingAgeFemale: 230,
};

export const initialVitalEvents: VitalEventRecord[] = [
  // --- បញ្ជីសម្រាល / កើត (Births) ---
  {
    id: 1,
    type: 'birth',
    personName: 'ជី សុខា',
    gender: 'ប',
    eventDate: '12/01/2026',
    category: 'party',
    fatherName: 'ជី ភា',
    motherName: 'សាន ឡៃហ៊ុន',
    groupNo: 1,
    houseNo: '12',
    remarks: 'សម្រាលនៅមណ្ឌលសុខភាពបន្ទាយស្ទោង ទម្ងន់ 3.2kg សុខភាពល្អ',
  },
  {
    id: 2,
    type: 'birth',
    personName: 'ស៊ឹម រតនា',
    gender: 'ស',
    eventDate: '28/01/2026',
    category: 'party',
    fatherName: 'ស៊ឹម សុង',
    motherName: 'ឆៃ ភាន',
    groupNo: 1,
    houseNo: '08',
    remarks: 'សម្រាលកូនស្រី សុខភាពមាំមួនល្អ',
  },
  {
    id: 3,
    type: 'birth',
    personName: 'ជឿន ពិសិដ្ឋ',
    gender: 'ប',
    eventDate: '14/02/2026',
    category: 'party',
    fatherName: 'ជឿន ជិត',
    motherName: 'ជឿន ថាង',
    groupNo: 2,
    houseNo: '19',
    remarks: 'គ្រួសារបក្សក្រុមទី២ ទម្ងន់ 3.4kg',
  },
  {
    id: 4,
    type: 'birth',
    personName: 'ខាន់ ស្រីមុំ',
    gender: 'ស',
    eventDate: '02/03/2026',
    category: 'general',
    fatherName: 'ខាន់ សុផល',
    motherName: 'សន ចាន់ថន',
    groupNo: 3,
    houseNo: '24',
    remarks: 'ប្រជាជនទូទៅ សុខភាពល្អ',
  },
  {
    id: 5,
    type: 'birth',
    personName: 'ណាង វាសនា',
    gender: 'ប',
    eventDate: '19/03/2026',
    category: 'party',
    fatherName: 'ណាង រ៉ន',
    motherName: 'ខៀវ ផល្លី',
    groupNo: 4,
    houseNo: '31',
    remarks: 'គ្រួសារបក្សក្រុមទី៤',
  },
  {
    id: 6,
    type: 'birth',
    personName: 'ឡុង កល្យាណ',
    gender: 'ស',
    eventDate: '08/04/2026',
    category: 'party',
    fatherName: 'ឡុង វិបុល',
    motherName: 'អ៊ុំ សុគន្ធា',
    groupNo: 5,
    houseNo: '45',
    remarks: 'សម្រាលនៅមន្ទីរពេទ្យបង្អែកស្ទោង',
  },
  {
    id: 7,
    type: 'birth',
    personName: 'ប៉ែន ករុណា',
    gender: 'ប',
    eventDate: '25/04/2026',
    category: 'general',
    fatherName: 'ប៉ែន វុទ្ធី',
    motherName: 'អ៊ុក សុភា',
    groupNo: 6,
    houseNo: '52',
    remarks: 'ប្រជាជនទូទៅ សុខភាពល្អធម្មតា',
  },
  {
    id: 8,
    type: 'birth',
    personName: 'យិន ធីតា',
    gender: 'ស',
    eventDate: '11/05/2026',
    category: 'party',
    fatherName: 'យិន ផល្លា',
    motherName: 'មុំ ស្រីរ័ត្ន',
    groupNo: 7,
    houseNo: '60',
    remarks: 'គ្រួសារបក្សក្រុមទី៧ កូនស្រីទី២',
  },
  {
    id: 9,
    type: 'birth',
    personName: 'ទូច សម្បត្តិ',
    gender: 'ប',
    eventDate: '03/06/2026',
    category: 'general',
    fatherName: 'ទូច ចាន់ណា',
    motherName: 'ម៉ៅ វណ្ណា',
    groupNo: 8,
    houseNo: '67',
    remarks: 'ប្រជាជនទូទៅ',
  },
  {
    id: 10,
    type: 'birth',
    personName: 'សេង ស្រីលីន',
    gender: 'ស',
    eventDate: '22/06/2026',
    category: 'party',
    fatherName: 'សេង គឹមសាន',
    motherName: 'ស៊ន ម៉ាលីស',
    groupNo: 9,
    houseNo: '73',
    remarks: 'គ្រួសារបក្សក្រុមទី៩ សុខភាពល្អ',
  },
  {
    id: 11,
    type: 'birth',
    personName: 'ម៉ែន ដារ៉ូ',
    gender: 'ប',
    eventDate: '09/07/2026',
    category: 'party',
    fatherName: 'ម៉ែន សុផល',
    motherName: 'កែវ ពិសី',
    groupNo: 11,
    houseNo: '85',
    remarks: 'គ្រួសារបក្សក្រុមទី១១',
  },
  {
    id: 12,
    type: 'birth',
    personName: 'ហេង ស្រីនីត',
    gender: 'ស',
    eventDate: '28/07/2026',
    category: 'general',
    fatherName: 'ហេង គង់',
    motherName: 'គង់ ណារី',
    groupNo: 14,
    houseNo: '102',
    remarks: 'ប្រជាជនទូទៅ',
  },
  {
    id: 13,
    type: 'birth',
    personName: 'ឆែម ច័ន្ទមុនី',
    gender: 'ស',
    eventDate: '15/08/2026',
    category: 'party',
    fatherName: 'ឆែម វុទ្ធី',
    motherName: 'អ៊ុន ផល្លា',
    groupNo: 17,
    houseNo: '116',
    remarks: 'គ្រួសារបក្សក្រុមទី១៧',
  },
  {
    id: 14,
    type: 'birth',
    personName: 'សួស សុខលី',
    gender: 'ស',
    eventDate: '04/09/2026',
    category: 'general',
    fatherName: 'សួស ចាន់រ៉ា',
    motherName: 'តាំង ស្រីម៉ៅ',
    groupNo: 20,
    houseNo: '121',
    remarks: 'ប្រជាជនទូទៅ កូនស្រី',
  },

  // --- បញ្ជីមរណភាព (Deaths) ---
  {
    id: 101,
    type: 'death',
    personName: 'ឃុន មន',
    gender: 'ស',
    age: 72,
    eventDate: '18/02/2026',
    category: 'party',
    causeOfDeath: 'ជរាពាធ',
    groupNo: 1,
    houseNo: '05',
    remarks: 'សមាជិកបក្សចាស់ជរា បានធ្វើបុណ្យតាមប្រពៃណី',
  },
  {
    id: 102,
    type: 'death',
    personName: 'អ៊ុក ស៊ាង',
    gender: 'ប',
    age: 81,
    eventDate: '26/03/2026',
    category: 'party',
    causeOfDeath: 'ជរាពាធ',
    groupNo: 5,
    houseNo: '38',
    remarks: 'សមាជិកបក្សអតីតយុទ្ធជន',
  },
  {
    id: 103,
    type: 'death',
    personName: 'ប៉ូច វណ្ណី',
    gender: 'ស',
    age: 64,
    eventDate: '15/05/2026',
    category: 'general',
    causeOfDeath: 'ជំងឺលើសឈាម និងបេះដូង',
    groupNo: 8,
    houseNo: '62',
    remarks: 'ប្រជាជនទូទៅ',
  },
  {
    id: 104,
    type: 'death',
    personName: 'នួន ហ៊ីម',
    gender: 'ប',
    age: 78,
    eventDate: '02/07/2026',
    category: 'party',
    causeOfDeath: 'ជរាពាធ',
    groupNo: 12,
    houseNo: '88',
    remarks: 'សមាជិកបក្សស្មោះត្រង់',
  },
  {
    id: 105,
    type: 'death',
    personName: 'សយ វ៉ាន់ថន',
    gender: 'ប',
    age: 53,
    eventDate: '19/07/2026',
    category: 'general',
    causeOfDeath: 'គ្រោះថ្នាក់ចរាចរណ៍',
    groupNo: 15,
    houseNo: '107',
    remarks: 'ប្រជាជនទូទៅ',
  },
  {
    id: 106,
    type: 'death',
    personName: 'ម៉ៅ គឹមឡេង',
    gender: 'ស',
    age: 69,
    eventDate: '29/08/2026',
    category: 'party',
    causeOfDeath: 'ជំងឺរ៉ាំរ៉ៃ',
    groupNo: 18,
    houseNo: '119',
    remarks: 'សមាជិកបក្សក្រុមទី១៨',
  },
];
